name: TheBinaryBananas

version: 0.0.1

model-paths:
  - models

test-paths:
  - test

analysis-paths:
  - analysis

macro-paths:
  - macros

snapshot-paths:
  - snapshots

asset-paths:
  - assets

target-path: target
log-path: logs

clean-targets:
  - target
  - dbt_modules

models:
    enabled: true
    materialized: table
